import asyncio
import json
import ssl
import urllib.request
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel

from app.config import settings, _get_gemini_key
from app.core.deps import get_current_user
from app.models.all_models import User

router = APIRouter(prefix="/api/ai", tags=["AI Assistance"])

class ImproveEnglishRequest(BaseModel):
    text: str
    context: Optional[str] = None

class ImproveEnglishResponse(BaseModel):
    original_text: str
    improved_text: str

def _call_gemini_api(api_key: str, prompt: str) -> str:
    models = ["gemini-flash-latest", "gemini-pro-latest"]
    last_err = None

    for model in models:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
        data = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": 0.1,
                "maxOutputTokens": 1200
            }
        }
        req = urllib.request.Request(
            url,
            data=json.dumps(data).encode("utf-8"),
            headers={"Content-Type": "application/json"}
        )
        ctx = ssl.create_default_context()
        try:
            with urllib.request.urlopen(req, context=ctx, timeout=25) as response:
                res = json.loads(response.read().decode("utf-8"))
                candidates = res.get("candidates", [])
                if candidates:
                    parts = candidates[0].get("content", {}).get("parts", [])
                    if parts:
                        improved = parts[0].get("text", "").strip()
                        # Clean any surrounding markdown fences if present
                        if improved.startswith("```") and improved.endswith("```"):
                            lines = improved.split("\n")
                            if len(lines) >= 2:
                                improved = "\n".join(lines[1:-1]).strip()
                        if improved:
                            return improved
        except Exception as e:
            last_err = e
            continue

    if last_err:
        raise last_err
    raise RuntimeError("No candidate response generated by Gemini AI.")

@router.post("/improve-english", response_model=ImproveEnglishResponse)
async def improve_english(
    payload: ImproveEnglishRequest,
    current_user: User = Depends(get_current_user)
):
    text_to_improve = payload.text.strip()
    if not text_to_improve:
        raise HTTPException(status_code=400, detail="Text cannot be empty.")

    if len(text_to_improve) > 5000:
        raise HTTPException(status_code=400, detail="Text exceeds maximum allowed length (5000 characters).")

    api_key = settings.GEMINI_API_KEY or _get_gemini_key()
    if not api_key:
        raise HTTPException(status_code=500, detail="Gemini API Key is not configured on server.")

    context_clause = f"Field Context: {payload.context}\n" if payload.context else ""
    prompt = (
        "You are an expert English communications editor for Geeta University Dean of Student Welfare (DSW) portal.\n"
        "Your task is to refine, correct, and improve the user's English text while STRICTLY preserving its exact meaning, tone, specific names, numbers, dates, and factual details without inventing or hallucinating any extra information.\n"
        "Fix all grammar, spelling, punctuation, capitalization, and awkward sentence structures to make it articulate, polite, and professional.\n"
        f"{context_clause}"
        "CRITICAL INSTRUCTION: Return ONLY the final improved text directly. Do NOT include any intro, markdown block quotes, explanations, options, or conversational commentary.\n\n"
        f"Original Text to improve:\n{text_to_improve}"
    )

    try:
        improved = await asyncio.to_thread(_call_gemini_api, api_key, prompt)
        return ImproveEnglishResponse(
            original_text=text_to_improve,
            improved_text=improved
        )
    except Exception as e:
        print(f"[AI Improve English Error] {e}")
        raise HTTPException(status_code=502, detail=f"Failed to improve English with AI: {str(e)}")
